### ISSUE TITLE
What about using ContextMenu

### ISSUE THREAD

**Issue by Ekinoxx0** [XJMLN/fivem-ctOS#1]
Hi, I was just curious about your project and seeing how your trying to interact with the world in general (Entity / Vehicle)

I would suggest you take a look at this resource to make interacting with entities more smooth : https://github.com/Kiminaze/ContextMenu

If this is not what your want your menu to look like you can just ignore this suggestion :)

**Comment by XJMLN** [comment]
In future versions of resource there will be interaction menu based on NUI, but thanks for your suggestion. :)
